# Generated by Django 4.2.3 on 2023-07-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Payment_method', models.CharField(max_length=32)),
            ],
        ),
    ]
